### PR TITLE
#2 Upgrade modernizer Maven plugin to 1.5.0.

### PR DESCRIPTION
**Pull request by krisztiankocsis**

### CODE REVIEW

**Comment by simonharrer** [comment]
Thank you for your PR. 

Hm, maybe we should enable setting regex according to `Collection<Pattern> exclusionPatterns` of the maven plugin. 

> <exclusionPatterns> violation patterns to disable. Each exclusion should be a regular expression that matches the javap format: java/lang/.*.

I want to keep the features similar between the maven and the Gradle plugin. Would that be ok with you? It could be done similar to the other options, we just need to convert the strings to patterns.

**Comment by krisztiankocsis** [comment]
Ok, I'll do it in the next couple of days, depending on free time

**Comment by krisztiankocsis** [comment]
Done

**Comment by simonharrer** [comment]
Looks good. I will update the README accordingly.

**Comment by simonharrer** [comment]
New release `1.5.0-1` has been made.

**Pull request merged**
